package main.java.com.caci.resources.exceptions;

// Exception class wrapper for assemble method
public class AssembleException extends Exception {

	/**
	 * Auto generated by IDE
	 */
	private static final long serialVersionUID = 5637084648534637460L;

	// call exception parent constructor
	public AssembleException(String s) {
		super(s);
	}

}