package main.java.com.caci.resources.exceptions;

// Exception class wrapper for split method
public class SplitException extends Exception {
	
	/**
	 * Auto-generated by IDE
	 */
	private static final long serialVersionUID = -2653713504329320910L;

	// call exception parent constructor
	public SplitException(String s) {
		super(s);
	}

}
